### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by that1cutie** [vali20/network-load-balancer#1]
Hello, I am very interested in using this program you've created but I cannot seem to compile it. I have cloned the repo through git onto my machine but I don't understand what to do from there. I understand this isn't really an issue with the program itself but I would greatly appreciate some help.

**Comment by gvanem** [comment]
It's easy. Do `msbuild -nologo -p:Configuration=Release -p:Platform="%CPU%" NetworkLoadBalancer.sln`.
Assuming you have a `CPU=x64` (or `CPU=x86`) in your environment.

**Comment by that1cutie** [comment]
Thank you so much. I'm still learning how to compile and I tried to compile this with go and with cmake (which i don't understand yet either), neither worked. I'm installing MSVS now. I'm actually surprised I didn't already have this installed.
